Job Client
----------

The client is a worker that executes jobs from the Job Server.


HOW TO BUILD?
-------------
I've provided a simple maven build script.
So running with maven installed should be a simple:

+$ mvn verify+

Running it can then be something like:

+$ java -jar target/JobClient-1.0-SNAPSHOT.jar -v -v bla.cfg+

Wher the "-v" lets you see more outputs and the "bla.cfg" specifies the configuration file to use.

A sample configuration file looks like this:

....
[worker]
name=Hans
port=4711
....


LICENSE
-------

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, see <http://www.gnu.org/licenses/>

